### ISSUE TITLE
Incomplete release 1.2.1

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#134] opened 2020-09-16 18:21 UTC
* Need to merge hotfix r1.2.1 into develop (can be done after merging r1.2.2 to master). Carefully see which functions had the conflicts, to avoid too much work and allowing all branches of develop to be automatically merged
* When testing r1.2.1, found an error when stopping after ASL - 060_ProcessM0 and rerunning again. This had to do with the ms to seconds conversion -> BIDS to ExploreASL internal.
@jan-petr you want to check this one?

**Comment by jan-petr** [comment] 2020-09-17 08:30
OK. Let's do this:

1. Jan merges hotfix1.2.2 to master according to the Workflow guide.
2. Jan merges master (with hotfixes 1.2.1 and 1.2.2) back to develop and resolves the errors. Nobody else touches the develop at the same time. In case of doubt - contact Henk.
3. Henk needs to describe what exactly is wrong in the 1.2.1 - what dataset, on what line stopped exactly, what was the error - crash, wrong function, wrong numbers at the end etc. so that I can reproduce this - once I find the error, we will discuss if this is a hotfix or a goes to 1.3.0

**Comment by jan-petr** [comment] 2020-09-17 09:30
List of conflicts:
CONFLICT (rename/rename): Rename "VERSION_1.1.2"->"VERSION_1.2.0" in branch "HEAD" rename "VERSION_1.1.2"->"VERSION_1.2.2" in "master"
Auto-merging README.md
Auto-merging Modules/xASL_module_Population.m
Auto-merging Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
CONFLICT (content): Merge conflict in Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
Auto-merging Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
CONFLICT (content): Merge conflict in Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
Auto-merging Modules/SubModule_Population/xASL_stat_GetAcquisitionTime.m
Auto-merging Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
CONFLICT (content): Merge conflict in Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
Auto-merging Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
Auto-merging Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
CONFLICT (content): Merge conflict in Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
Auto-merging Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
Auto-merging Functions/xASL_vis_VisualQC_TopUp.m
Auto-merging Functions/xASL_vis_TransformData2View.m
Auto-merging Functions/xASL_vis_OverlapT1_ASL.m
Auto-merging Functions/xASL_vis_Imwrite.m
Auto-merging Functions/xASL_vis_CropParmsApply.m
Auto-merging Functions/xASL_vis_CropParmsAcquire.m
Auto-merging Functions/xASL_vis_CreateVisualFig.m
Auto-merging Functions/xASL_vis_AddIM2QC.m
Auto-merging Functions/xASL_str2num.m
CONFLICT (content): Merge conflict in Functions/xASL_str2num.m
Auto-merging Functions/xASL_quant_M0.m
CONFLICT (content): Merge conflict in Functions/xASL_quant_M0.m
Auto-merging Functions/xASL_init_LoadMetadata.m
CONFLICT (content): Merge conflict in Functions/xASL_init_LoadMetadata.m
Auto-merging Functions/xASL_im_MaskPeakVascularSignal.m
Auto-merging Functions/xASL_bids_parms2BIDS.m
CONFLICT (content): Merge conflict in Functions/xASL_bids_parms2BIDS.m
Auto-merging Functions/xASL_adm_CleanUpBeforeRerun.m
Auto-merging External/SPMmodified/xASL/xASL_io_Nifti2Im.m
CONFLICT (content): Merge conflict in External/SPMmodified/xASL/xASL_io_Nifti2Im.m
Auto-merging External/README_SPM.txt
CONFLICT (content): Merge conflict in External/README_SPM.txt
Auto-merging ExploreASL_Initialize.m
CONFLICT (content): Merge conflict in ExploreASL_Initialize.m
Auto-merging ExploreASL_ImportConfig.m
CONFLICT (content): Merge conflict in ExploreASL_ImportConfig.m
Auto-merging Development/xASL_qc_TestExploreASL_HM.m
CONFLICT (content): Merge conflict in Development/xASL_qc_TestExploreASL_HM.m
Auto-merging Development/xASL_qc_TestExploreASL.m
Auto-merging Development/ExploreASL_make_standalone/ExploreASL_make_standalone.m
CONFLICT (content): Merge conflict in Development/ExploreASL_make_standalone/ExploreASL_make_standalone.m
Auto-merging Development/BIDS/load2bids.m
CONFLICT (content): Merge conflict in Development/BIDS/load2bids.m
Auto-merging CHANGES.md
CONFLICT (content): Merge conflict in CHANGES.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by HenkMutsaerts** [comment] 2020-09-17 11:15
OK, I suggest to merge by cherry-picking, so you can merge issue-by-issue, which makes it easier to check what is newer and what not. Not your complete list were conflicts, only these:

Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
Functions/xASL_str2num.m
Functions/xASL_quant_M0.m
Functions/xASL_init_LoadMetadata.m
Functions/xASL_bids_parms2BIDS.m
External/SPMmodified/xASL/xASL_io_Nifti2Im.m
External/README_SPM.txt
ExploreASL_Initialize.m
ExploreASL_ImportConfig.m
Development/xASL_qc_TestExploreASL_HM.m
Development/ExploreASL_make_standalone/ExploreASL_make_standalone.m
Development/BIDS/load2bids.m
CHANGES.md

**Comment by jan-petr** [comment] 2020-09-17 13:03
Cherry picking way to time consuming. Already now it took a lot of time and cherry picking would give the extra overhead of merging all issues. All the issues below were resolved but one. There, the problem was not what was newer, but how to merge the conflicting edits. See more info below.

> CONFLICT (rename/rename): Rename "VERSION_1.1.2"->"VERSION_1.2.0" in branch "HEAD" rename "VERSION_1.1.2"->"VERSION_1.2.2" in "master"

Kept the new version.

> CONFLICT (content): Merge conflict in CHANGES.md

The main reason was that in master, many details were filled in. So deleted the old version with not much details. Should be hopefully all good and nice.

> CONFLICT (content): Merge conflict in Development/BIDS/load2bids.m

I simply took the DEVELOP version which was more recent.

> CONFLICT (content): Merge conflict in Development/xASL_qc_TestExploreASL_HM.m

I simply took the version with more complete input arguments

> CONFLICT (content): Merge conflict in Development/ExploreASL_make_standalone/ExploreASL_make_standalone.m

There were cosmetic edits in master, so easy to merge.

> CONFLICT (content): Merge conflict in ExploreASL_ImportConfig.m

Michael updated 'incoming' and master added 'ADNI' - non-conflicting change at the end.

> CONFLICT (content): Merge conflict in ExploreASL_Initialize.m

Keeping the develop version as newer edit.

> CONFLICT (content): Merge conflict in External/README_SPM.txt

Keeping the non-conflicting addition from the develop branch.

> CONFLICT (content): Merge conflict in External/SPMmodified/xASL/xASL_io_Nifti2Im.m

Keeping the newer version that skips the empty files

> CONFLICT (content): Merge conflict in Functions/xASL_bids_parms2BIDS.m

Keeping the newer hotfix version, conflict was probably cosmetic.

> CONFLICT (content): Merge conflict in Functions/xASL_init_LoadMetadata.m

Keeping the newer edits from the develop branch. Conflict was probably cosmetic.

> CONFLICT (content): Merge conflict in Functions/xASL_quant_M0.m

Keep the hotfix version that now replaces the code with a new subfunction xASL_quant_SliceReadoutTime_ShortestTR.

> CONFLICT (content): Merge conflict in Functions/xASL_str2num.m

Keeping the develop version with newer header. Conflict probably only cosmetic.

> CONFLICT (content): Merge conflict in Modules/SubModule_ASL/xASL_wrp_RegisterASL.m

Keeping the newer develop-version. Conflict was probably only cosmetic.

> CONFLICT (content): Merge conflict in Modules/SubModule_Population/xASL_adm_GzipAllFiles.m

Keeping the hotfix version that is obviously the newer and fixes the error. Unclear why there was a conflict

> CONFLICT (content): Merge conflict in Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m

Keeping the correct hotfix except for the style of two output messages.

**CONFLICT (content): Merge conflict in Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m**

**Needs to be resolved by Henk**

**Comment by jan-petr** [comment] 2020-09-17 16:16
Resolved all issues between hotfix 1.2.1 and 1.2.2 branches. Additionally, I had to synchronize the changes.md back with master. All this should now be in sync. And develop is now indicated as being able to be merged to master without issue.

**Closed by jan-petr** 2020-09-17 16:16 UTC
Labels: bug
