### ISSUE TITLE
Quantification is off for test cases

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#73] opened 2020-08-03 20:23 UTC
When testing the ASL quantification between v1.2.0 and 2 weeks before v1.0.0, I noticed the following (providing a summary here):

## Factor 2 higher CBF values in 1.2.0 compared to pre-1.0.0
* Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ

## CBF values factor 2 too low
* Philips_2DEPI_Lesion_NoFLAIR_LoQ
* Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ
* Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ

See my e-mail dd 03-08-2020 for details

**Comment by jan-petr** [comment] 2020-08-11 17:25
1) Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ
Problem GM-WM stays the same but average ASL CBF becomes 2 times as high -> scale slope issue? So can you check if there is a potential scale slope issue that can explain the factor 2 for Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ between old and new version, did you do a scale slope improvement?

Answer: qCBF in standard space identical to 1.2 and 1.0 except for minor registration differences cause by a different T1 processing. ASL4D in this dataset comes as quantified values and quantification is turned off. CBF and ASL4D in native space are completely identical. So I have no idea where you obtained the difference I was not able to reproduce it. I don't see any discrepancy in the table itself neither. All versions show the same number - 41 and not 82.

ACTION: Henk finds out where he gets 82. But probably no action needed

2) Philips_2DEPI_Lesion_NoFLAIR_NoM0_LoQ
Answer: Rather wrong dataset. All version on LowQ produce a very shitty segmentation - completely unusable. Minor difference in 1.2 and 1.0 in segmentation, but both are bad. HighQ in 1.2 is working rather good. The are differences in ASL-T1w registration. 1.2.0HighQ is definitively the best in ASL-T1w and in segmentation. What's a bit strange to me is that PV_GM in the standard space doesn't seem to be smoothed to the ASL resolution - any chance we have been changing this?

ACTION: We change this dataset to highQ and we probably replace it by some other dataset with nicer CBF as it is really low here because of whatever reason.

3) Philips_2DEPI_Segmentation_on_2D_T2
Answer: CBF image is mostly the same for all. ASL-T1w registration is shitty for 1.2.0, but it is much more shitty for 1.0.0. For 1.2.0H, it is almost perfect. This can easily explain the difference.

ACTION: 1.2.0 is better and 1.2.0H even more. Lets be happy about that and not take it as an error. I would vote for activating the HighQ for this testing set as the registration ASL-T1w is too shitty to take it for comparisons and we will have issues with that in the future. Lets take highQ version.

4) Philips_3DGRASE_FLAIR_M0
Answer: CBF images equivalent. Segmentation rather shitty, especially in the frontal lobe for version 1.0.0. Version 1.1.2 and 1.2.0 fixes it and give a very nice segmentation.

ACTION: Perfect, the newer version works better and this probably explains also the CBF difference. Lets not do anything and take the newer version.

**Comment by jan-petr** [comment] 2020-08-18 17:20
@HenkMutsaerts To close the issue #73, you need to do the following steps (I don't have write access to the surfdrive):

1) Take the current resultsTable as the new standard as it has changed for two datasets
(Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ, and
Philips_3DGRASE_FLAIR_M0)

And we're happy about the change :)

2) The dataset Philips_2DEPI_Segmentation_on_2D_T2_LoQ needs to be renamed to HiQ and the .json file updated accordingly.

3)  Philips_2DEPI_Lesion_NoFLAIR_NoM0_LoQ

This dataset needs to be replaced by the following one:
https://cloud.hzdr.de/s/zJKE6iqBp35WTEw
It's from the same study so you don't have to change the datapar. And parameter needs to be put at HiQ.

**Comment by HenkMutsaerts** [comment] 2020-08-19 05:07
OK I did these changes, can you check the following point under 2.
* What's a bit strange to me is that PV_GM in the standard space doesn't seem to be smoothed to the ASL resolution - any chance we have been changing this?
* I should input any new options that we have created

**Comment by jan-petr** [comment] 2020-08-19 10:11
Perfect. Looks all good. I will re-test everything with release 1.2.0 - to see if all runs and looks good. The thing with point 2 is a bit strange. I will try to check that.

Yes about the options - I will try to keep track in the future.

**Closed** 2020-09-01 16:16 UTC
Labels: help wanted
