### ISSUE TITLE
Create DICOM2ASL-BIDS app

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#163] opened 2020-09-28 08:47 UTC
* Create script based on ExploreASL_Import.m that outputs to ASL-BIDS
* Create a conversion script ExploreASL_Import2BIDS
* Insert some functionality from GSP flavors

**Comment by HenkMutsaerts** [comment] 2020-10-28 12:52
Some other things we discussed:

Put all 40 flavors on GitHub, anonymized, and develop import on these

Program code in Matlab as compiled app with runtime, use ExploreASL GUI in Python

INPUT ASL-BIDS information
1) DICOM tags
2) scanner exam card export (need to write a reader)
3) DICOM-tag containing XX (Philips), Phoenix (Siemens) -> can get lost in anonymization -> what is the logic of the scale slopes, could we estimate them, in a combination of the magnetization values from (coming from the gain/ACDC)
4) Prior information (GE product sequence especially, only a few options)
5) Automatic detection background suppression 
 			-> order of magnitude difference between subtracted & unsubtracted signal
 			-> on 2D EPI Z-axis gradient on unsubtracted
 			-> tissue contrast subtracted vs unsubtracted
6) Automatic detection M0 image

-> in future, use Phoenix / Philips XX import

**Comment by jan-petr** [comment] 2020-10-29 18:43
> Put all 40 flavors on GitHub, anonymized, and develop import on these

There is a separate issue for this number 178.

> Program code in Matlab as compiled app with runtime, use ExploreASL GUI in Python

Yes, the design should be compatible with the GUI.

> 1. DICOM tags

Yes - like the previous import.

> 2. scanner exam card export (need to write a reader)

Created a new issue for this - Advanced DICOM2BIDS import - issue 194 in milestone 1.5.0

> 3. DICOM-tag containing XX (Philips), Phoenix (Siemens) -> can get lost in anonymization -> what is the logic of the scale slopes, could we estimate them, in a combination of the magnetization values from (coming from the gain/ACDC)

XX and Phoenix are answered below. Missing scale slopes are lost IMHO - if you have an idea, lets make it a separate issue.

> 4. Prior information (GE product sequence especially, only a few options)

Yes - like in the normal ExploreASL import.

> 5. Automatic detection background suppression
>    -> order of magnitude difference between subtracted & unsubtracted signal
>    -> on 2D EPI Z-axis gradient on unsubtracted
>    -> tissue contrast subtracted vs unsubtracted

Created a new issue for this - Automatic detection of background suppression - issue 195 in milestone 1.5.0. But that's something I would put in the ASL module, and not in import.

> 6. Automatic detection M0 image

Created a new issue for this - Advanced DICOM2BIDS import - issue 194 in milestone 1.5.0

> -> in future, use Phoenix / Philips XX import

Created a new issue for this - Advanced DICOM2BIDS import - issue 194 in milestone 1.5.0

**Comment by jan-petr** [comment] 2020-10-29 18:46
Instead of the 1000 issues merged to one - as above :) I propose to do the following:

1. ImportConfig - this is skipped and imPar structure is saved directly as a JSON file.

2. Data files 
	- add imPar.json/ImagePar.json to each directory instead of hardcoded in the script
	- add studyPar.json to each directory instead of hardcoded in the script
	- move most hardcoded parameters to JSON files and prune the JSON files
	
3. xASL_qc_TestBidsConversion
	- runs conversion for all directories in the 40 flavors. Based on the loadBids and containing all the manual stuff
	
4. ExploreASL_ImportBIDS 
	- contains all the ExploreASLimport and loadbids.m joint together
	- Has three submodules
		- ImportData to NIFTI
		- NIFTI to ASL-BIDS
		- full anonymization (including defacing)
		- they are run separately in case a manual interaction is needed to fix between DICOM to NII and NII to BIDS

**Comment by jan-petr** [comment] 2020-10-29 22:48
* ImportConfig excluded
* ImPar loaded directly from file for all 40 flavors
* The first part of ExploreASL_ImportBIDS that exports from DICOM to NII is now working.

**Comment by HenkMutsaerts** [comment] 2020-11-21 18:24
Nice work, I agree but:
* would label all BIDS issues with BIDS, and name the functions xASL_bids_ (rather than _qc_)
* while we may of course also do the M0 detection, bsup detection in quantification for QC, it would also be good to have this in the DICOM2BIDS conversion, just to validate all BIDS fields as good as we can, before running the pipeline. The user should have to do some manual checks in the conversion, not in the pipeline.

**Comment by jan-petr** [comment] 2020-11-25 13:47
@HenkMutsaerts Yes, agree with the label and function names. The _qc_ was there only because we had this in the function that compared the 10 datasets, but I have renamed it now also to _bids_

Regarding M0 detection and Bsup detection - yes, these are separate issues now.

**Comment by jan-petr** [comment] 2020-11-25 13:51
@MichaelStritt I am still doing some updates, but once I am done. These two things need to be fixed:

Concerning xASL_bids_Compare
- When numeric arrays are compared and differ, the printed result is super long and messy. It would be good to correctly format it and shorten the report.
- Annoying issue is that isequal function is used for numeric - this is simple and has many advantages, but it also reports differences smaller than, e.g. 10e-6. We can probably skip those.

Concerning json_write - for a lot of DICOM parameters (e.g. often for EffectiveEchoSpacing, sliceTime and much more - discovered by the BIDS compare), it does happen that the numeric value of 0.03 is written like 0.02999999999999. I tried to change the num2str at the end of json_write to limit this to precision 12, but this only shifted the problem. It would be great to find out why this might be happening, why are some numbers so imprecise in the DICOM and if we can do something about it - more than a simple rounding.

**Comment by MichaelStritt** [comment] 2020-11-30 10:53
Hey @jan-petr, I used `xASL_bids_CompareStructures` on some of the original DICOMs from the **flavor library**. I noticed a warning caused by **duplicate keys**. I checked the files and saw that you're using `LabelingLocationDescription` multiple times in the same JSON. Just to let you know :)

**Comment by MichaelStritt** [comment] 2020-11-30 11:25
Check matrix dimensions fix:

![Capture](https://user-images.githubusercontent.com/46593074/100604611-0c5ad880-3307-11eb-92b6-c2a24cfc4769.PNG)

**Comment by MichaelStritt** [comment] 2020-11-30 12:15
Compare numeric arrays:

![Capture](https://user-images.githubusercontent.com/46593074/100609253-fa306880-330d-11eb-9cb1-5c3edf4e6939.PNG)

Probably not the most sophisticated solution, but I like the look. If you'd prefer to see all array elements I can change it though @jan-petr 👍

**Comment by MichaelStritt** [comment] 2020-11-30 12:21
> Concerning json_write - for a lot of DICOM parameters (e.g. often for EffectiveEchoSpacing, sliceTime and much more - discovered by the BIDS compare), it does happen that the numeric value of 0.03 is written like 0.02999999999999. I tried to change the num2str at the end of json_write to limit this to precision 12, but this only shifted the problem. It would be great to find out why this might be happening, why are some numbers so imprecise in the DICOM and if we can do something about it - more than a simple rounding.

This could be data type related. I'll try to reproduce the error and I'll have a look at it, no promises though ;)

**Comment by MichaelStritt** [comment] 2020-11-30 12:46
Inserting **doubles** works fine for me:
```
x.Number = double(0.03);
x.Name = 'Michael';
spm_jsonwrite(filePath,x);
```
```
{
"Number":0.03,
"Name":"Michael"
}
```
Inserting **singles** really seems to be a problem:
```
x.Number = single(0.03);
x.Name = 'Michael';
spm_jsonwrite(filePath,x);
```
```
{
"Number":0.0299999993294,
"Name":"Michael"
}
```

**Comment by MichaelStritt** [comment] 2020-11-30 12:55
My quick fix would be to use:
**json_write**, lines 228-230:
```
...
else
    S = num2str(double(json));
end
...
```
Haven't tested it for arrays, but works fine for simple cases like the one above.

**Comment by jan-petr** [comment] 2020-12-01 09:35
> Hey @jan-petr, I used `xASL_bids_CompareStructures` on some of the original DICOMs from the **flavor library**. I noticed a warning caused by **duplicate keys**. I checked the files and saw that you're using `LabelingLocationDescription` multiple times in the same JSON. Just to let you know :)

@MichaelStritt, an error during manual copy-pasting. Fixed - will send updated data later. Thanks for reporting, we need to get rid of as much warnings as possible.

Matrix dimensions and arrays now compare perfectly! It immediately helped me to uncover another error in the data :)

Good work fixing the 'rounding' issue.

**Comment by jan-petr** [comment] 2020-12-03 19:41
@MichaelStritt I have added the option to read the DICOMs under Mac using SPM_DICOMREAD instead of DCMTK.
See line 34 in xASL_io_DcmtkRead.m. This mostly works, but there are still some troubles with certain tags. Some tags are not correctly converted, some are somehow missing. 

I made sure that all that is read by DCMTK is added to the dicom dictionaries
_ExploreASL/External/xASL_DICOMLibrary.txt_ and to
_ExploreASL/External/SPMmodified/spm_dicom_dict.txt_
So there *should* be no need to add more tags. But maybe, the types are defined incorrectly. They should be fine in the MEX, but not necessarily here. If you change it, please do it in both dictionaries. And also call 
_spm_dicom_text_to_dict('spm_dicom_dict.txt')_
to apply the changes, as SPM reads the dictionary from the .mat file.

Can you please run
_xASL_bids_TestBidsConversion('.../BIDS','.../reference/',1,0);_
on the flavors database and see if this is completed without errors - both branches of the (ismac()). There were still some fields that were missing, incorrectly transformed etc. The reference database should be correct on all occasions - run the same function with 0,1 at the end.

The DCMTK version should only miss EffectiveEchoSpacing for some structural files - no idea what I have changed to accidentally remove it there. But it used to work some time ago. And somehow, two structural datasets are not correctly converted - but you probably don't need to loose too much time with that - I can fix that. Figuring out the errors and types for the version using SPM_DICOMREAD is more important.

No problem if you don't find a way to fix it in all cases - we can just write it up here and try to find solution together.

**Comment by jan-petr** [comment] 2020-12-03 20:35
Problem with missing EffectiveEchoSpacing fixed - it was zero in the old version, and I have excluded zeros in the new version from the output. I'll submit the code change and new reference datasets soon.

**Comment by jan-petr** [comment] 2020-12-03 20:52
Also - with DCMTK - Siemens_PCASL_3DGRASE_vascular takes for ages. Probably subsequent parsing of the Phoenix protocol - might be worth checking as we don't really need the Phoenix for every slice...

**Comment by jan-petr** [comment] 2020-12-03 21:14
@MichaelStritt The original DCMTK import of the whole flavors should be now completely OK with the updated data (sent per email). There were some errors, but upon re-running, they are mysteriously gone. But please try to check both the DCMTK version and also the SPM version. Thanks.

**Comment by jan-petr** [comment] 2020-12-04 12:04
@MichaelStritt When converting the full 40 flavors and then running the comparison. These missing files are reported:
=========================================
Dataset:		bids
Missing:		/sub-Sub1/anat
Missing:		/sub-Sub1/anat/sub-Sub1_T1w.json
Missing:		/sub-Sub1/anat/sub-Sub1_T1w.nii.gz
=========================================
Dataset:		Siemens_PCASL_volunteer
				No missing files
=========================================
AND

=================================
Dataset:		bids
Missing:		/sub-Sub1/anat/sub-Sub1_T2w.json
Missing:		/sub-Sub1/anat/sub-Sub1_T2w.nii.gz
===================================
Dataset:		Siemens_PCASL_2DEPI_pharma
				No missing files
=====================================

I'll have a look at that as well...

**Comment by MichaelStritt** [comment] 2020-12-09 13:55
### Tested:
GE_PCASL_2DEPI_volunteer: `Duplicate key` warning during import.
GE_PCASL_3Dspiral_Product_pharma: 👍 
GE_PCASL_3Dspiral_Product_volunteer: `Reference to non-existent field 'ASLContext'. ExploreASL_ImportBIDS (line 635).`
GE_PCASL_3Dspiral_WIP_pharma: `\sub-Sub103\perf\sub-Sub103_asl.nii.gz RMSE (1.693182e+00) of NIFTIs above threshold.`
GE_PCASL_3Dspiral_WIP_volunteer: `Different value: M0` & `Different value: IntendedFor`
GE_PCASL_3Dspiral_volunteer: 👍 
Philips_PCASL_2DEPI_Bsup_AD1: `Different value: M0` & `Different value: IntendedFor`
Philips_PCASL_2DEPI_Bsup_AD2: `Different value: M0` & `Different value: IntendedFor`
Philips_PCASL_2DEPI_Bsup_AD3: `Different value: M0` & `Different value: IntendedFor`
Philips_PCASL_2DEPI_Bsup_AD4: `Duplicate key`, `Inputs must be character vectors` & `Philips MR ScaleSlope` warning, `Different value: M0` & `Different value: IntendedFor`

------

Philips_PCASL_2DEPI_GBM
Philips_PCASL_2DEPI_Ingenia_volunteer
Philips_PCASL_2DEPI_Intera_volunteer
Philips_PCASL_2DEPI_dummyLL
Philips_PCASL_2DEPI_dummyMultiPLD
Philips_PCASL_2DEPI_dummyQUASAR
Philips_PCASL_2DEPI_glioma
Philips_PCASL_2DEPI_noBsup_AD
Philips_PCASL_2DEPI_pharma
Philips_PCASL_2DEPI_pharma2
Philips_PCASL_2DEPI_volunteer3
Philips_PCASL_2DEPI_volunteer_1
Philips_PCASL_2DEPI_volunteer_2
Philips_PCASL_3DGRASE_R5.4_TopUp
Philips_PCASL_3DGRASE_functional
Philips_PCASL_3DGRASE_volunteer
Siemens_PASL_2DEPI_noBsup_AD
Siemens_PASL_2DEPI_noBsup_AD2
Siemens_PASL_3DGRASE_AD
Siemens_PASL_3DGRASE_AD2
Siemens_PASL_3DGRASE_Prisma_Bsup_AD1
Siemens_PASL_3DGRASE_Prisma_Bsup_AD2
Siemens_PASL_3DGRASE_Prisma_Bsup_AD3
Siemens_PASL_multiTI
Siemens_PASL_singleTI
Siemens_PCASL_2DEPI_AD
Siemens_PCASL_2DEPI_pharma
Siemens_PCASL_2DEPI_volunteer
Siemens_PCASL_3DGRASE_AD
Siemens_PCASL_3DGRASE_vascular
Siemens_PCASL_3DGRASE_volunteer
Siemens_PCASL_3DGRASE_volunteer2
Siemens_PCASL_volunteer

**Comment by jan-petr** [comment] 2021-01-07 22:00
Code finished a it works perfectly on the Flavors. It even extracts certain parameters from the Phoenix protocol. 

There are still certain things to finish in issues #231, #232.

**Comment by jan-petr** [comment] 2021-01-11 21:18
I have checked and tested everything - thanks for the fixes Michael.

Last thing to do: I still need to fix this: xASL_bids_Par2JSON: confuses “parms” “parameters” “json”, please check for consistent use. The json file should be called “json sidecar” and the parms.mat file is the legacy ExploreASL parameter file.

For the separate BIDS app - there's new issue, will do that in 1.5.0.

**Comment by HenkMutsaerts** [comment] 2021-01-31 17:07
So is this now fixed:?

> `xASL_bids_Par2JSON: confuses “parms” “parameters” “json”, please check for consistent use. The json file should be called “json sidecar” and the parms.mat file is the legacy ExploreASL parameter file.

**Comment by jan-petr** [comment] 2021-02-01 08:58
Yes. That last thing is fixed - this was fixing only the comments.
All was previously very thoroughly tested - we have a special testing just for this conversion on the Flavors dataset and comparison with the reference conversion. So this is ready for merging - I'll do that as soon as I get the reviews.

**Closed** 2021-02-01 10:20 UTC
Labels: BIDS, Feature
