### ISSUE TITLE
Put ExploreASL on NITRC

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1523] opened 2023-10-23 17:36 UTC
### Description

ExploreASL is added to NITRC but still needs to be configured.

>>
Begin forwarded message:

From: noreply@nitrc.org
Subject: NITRC Tool/Resource Approved
Date: 25 July 2023 at 00:04:29 CEST
To: henkjanmutsaerts@gmail.com

Congratulations!  Your tool/resource registration for NITRC has been approved.

Tool/Resource Full Name:  ExploreASL
Tool/Resource Unix Name:  exploreasl

You can configure your tool/resource here: http://www.nitrc.org/wizard/index.php?group_id=1622.  Additional instructions can be found on the NITRC Community wiki at 
http://www.nitrc.org/getting_started.

For additional information, please see the NITRC FAQ at http://www.nitrc.org/faq 
and user guide at http://www.nitrc.org/help/user_guide.html, or contact us at 
moderator@nitrc.org.

--the NITRC team
>>

### Release notes

ExploreASL added to NITRC.

**Comment by maartenhammer** [comment] 2023-10-27 08:01
NITRC has an issue connecting with Github, the issue is known and should be fixed in 1-2 weeks. 
I have set a reminder to try again nov 13th.

> Hi Maarten,
> 
> Thanks for your message.
> 
> This appears to be due to another issue that we're fixing now; this fix should be out in a week or two.  I'll keep you posted.
> 
> Christian
> 
> NITRC

**Comment by HenkMutsaerts** [comment] 2024-01-31 14:57
@maartenhammer Did you follow-up on this?

**Comment by maartenhammer** [comment] 2024-01-31 15:45
@HenkMutsaerts They did not resolve the issue after about a month, so I manually configured the NITRC page to have links to "Download" at Zenodo, "Source Code" goes to Github, and "Docs" links to Github docs. As well as having a dockerhub link and a smal blurb describing the process. It should be about as complete as a external repository can be.

**Comment by maartenhammer** [comment] 2024-02-07 13:29
- [x] change Title zenodo.json
- [x] Check how NITRC fetches Pubmed? -> can't add things manually

**Closed as completed** 2024-02-19 14:51 UTC
Labels: feature
