### ISSUE TITLE
xASL_bids_Dicom2JSON fails in a GE deltam-m0scan situation

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#1133] opened 2022-07-30 23:28 UTC
### Description

Given a typical GE ASLContext scenario of: deltam, m0scan , this script incorrectly handles the `parmsIndex` variable, possibly due to the naming of the files "ASL4D_6_00001.json" (deltam) and "ASL4D_1_e00000_6_.json" (m0scan) having a matching 6 designation. 

This block seems to be responsible:

```matlab
			% First find the first matching seriesNumber
			parmsIndex = length(instanceNumberList);
			for iInst = length(instanceNumberList):-1:1
				if (currentSeriesNumber == seriesNumberList(iInst))
					parmsIndex = iInst;
				end
			end
```

`parmsIndex` is intially set to 2 due to the number of files. And since the `currentSeriesNumber` is going to be 6 for both files, the `parmsIndex` does not change. This leads to ASLContext being overwritten by the m0scan JSON. The resulting ASLContext becomes "m0scan, m0scan", and snowballs into other errors down the line during processing.

This seems to be present in both 1.9.0 and 1.10.0beta

Fixed a bug in which xASL_bids_Dicom2JSON did not correctly increment the parameter index due to DCM2NII outputting the same series number for each ASL JSON. 

[xASL_bids_Dicom2JSON_Issue.zip](https://github.com/ExploreASL/ExploreASL/files/9227742/xASL_bids_Dicom2JSON_Issue.zip)

### Tasks

- [x] Fix handling of `parmsIndex` in function `xASL_bids_Dicom2JSON.m`

### How to test

- See attached json files for testing
- `parmsIndex` should correctly change between 1 and 2. 

### Release notes

Duplicate. Fixed in #435.

**Comment by jan-petr** [comment] 2022-08-16 08:07
Thanks for reporting. And thanks for the ZIP - that really helps in case I can't have the DICOMs itself. 

You are right that the likely issue is the parmsIndex is not going through 1 and 2 as we are reading all the DICOMs. However, the issue is not the ``currentSeriesNumber`` - that is supposed to be always the same as this is only used to filter out data from a different Series. The key is the ``InstanceNumber`` - we have the ``InstanceNumberList`` that gives a list of InstanceNumbers per NII volumes. We are then going through all DICOMs and based on their Series and Instance Numbers, we assign them to the correct NII volume (as there are often more DICOMs per NII).

The issue in your case is that the InstanceNumber for the second volume is outputted incorrectly by dcm2nii - so that in the second JSON, there's no instance number given. Either that is missing in the DICOM, or something goes wrong in dcm2nii. You can check if the parameter ``temp.InstanceNumber`` is correctly incremented with each DICOM. Then we can try to fix the code so that the ``InstanceNumberList`` is correctly reinstated - and then the ``parmsIndex`` might work again. But you have to check that yourself, as this ``temp`` parameter is read for each DICOM - so I don't have access to that in the MAT file you've sent. A second option would be to specify ASLcontext in the studyPar.json and see if that will work out of the box.

**Comment by MauricePasternak** [comment] 2022-08-16 13:05
You just reminded me of an issue I had back with the Python GUI - indeed dcm2niix didn't correctly extract all sequence information from certain GE scans in the 2019 version that ExploreASL uses. In fact, that's why the old Python GUI started using this version of dcm2niix:

https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20201102

> Extract more sequence information for [GE](https://github.com/neurolabusc/dcm_qa_ge).

I will verify the `temp.InstanceNumber` suggestion you gave, but wanted to note this down before I forgot.

**Comment by MauricePasternak** [comment] 2022-08-17 21:49
Okay, so a couple of updates:

- Upgrading to the newest dcm2niix ([2022-07-20](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20220720)) does result in appropriate imports and ASLContexts.

- The above is not a true fix. The only reason it works is because I see that later on ExploreASL `parms{parmsIndex}` merges with `JSONParms` from the newer dcm2niix json file and that the latter (which has correct ImageType) takes priority in the merge. The issue on ExploreASL's side of populating `parms` still remains. Older versions of `dcm2niix` didn't read GE DICOM as meticulously, so that was half the problem. An update of dcm2niix is probably still needed, since the 2019 version currently in use would probably override any fix that's implemented by ExploreASL during the merging.

- Your hypothesis is correct: the main cause of this issue lies in `instanceNumberList`. It has a correct length of 2 (this is why indexing `parms` is successful when merging with `JSONParms`). But both array elements are `0` (the same). This messes up what `parmsIndex` becomes in earlier steps when ExploreASL looks through each dicom file. It stays at a value of `2` for the most part, resulting in only the 2nd cell of `parms` being populated/overwritten.

- Presumably this issue stems from handling the dcm2niix filenames output being too similar (see log file to see the original dcm2niix output filenames). The "cleaned" temp nifti and json files reflect the fact that only `SeriesNumber` (6 in this example) is accurately extracted.

![gnome-shell-screenshot-LJYQQ1](https://user-images.githubusercontent.com/57411571/185247921-03b0a0b0-0ba4-45c9-bd57-20378331e8d9.png)

[xASL_module_Import_sub-sub_009.log](https://github.com/ExploreASL/ExploreASL/files/9366188/xASL_module_Import_sub-sub_009.log)
 
Also attaching workspace @line 408
[xASL_bids_Dicom2JSON_line408.zip](https://github.com/ExploreASL/ExploreASL/files/9366217/xASL_bids_Dicom2JSON_line408.zip)

**Comment by MauricePasternak** [comment] 2022-08-26 18:04
@jan-petr I believe we can close this issue. Your changes to #435 allow for this particular flavor of GE scans to proceed correctly.

When breaking @ section (~line 416)

```matlab
                 for indexInstance = 1:length(parms)
			if instanceNumberList(indexInstance) > 0
				parmsIndex = indexInstance;
			end
			%% If no files were found previously (just directories etc.) then the manufacturer won't be identified and
			% dcmfields won't be assigned
			if exist('dcmfields','var')
```

It looks like `instanceNumberList` properly contains the right unique indices, leading to the other variable being correctly populated.

workspace image, in case you wanted to take a look: 
[xASL_bids_Dicom2JSON__from_feature-#435__line416.zip](https://github.com/ExploreASL/ExploreASL/files/9435353/xASL_bids_Dicom2JSON__from_feature-.435__line416.zip)

The only observation that I have left is that `ImageType` field in `c_all_parms` is empty for all elements in the vector except for the last. This is curious because `ImageType` is available in the dicom headers in all dicom files. Anyways, possibly a different issue, or this is intended behavior that I'm not aware of.

This issue is good to close.

**Comment by jan-petr** [comment] 2022-08-26 18:15
Thanks. Interesting - in my case, it properly filled both two subfields of c_all_parms correctly. Anyway - your behavior is very similar to the behavior in my own dataset (except the filling) and since it works and correctly identifies the ImageTypes at the end, then I would close this indeed. We have 10 GE flavors, so I should be able to notice if this happens again.

**Closed by jan-petr** 2022-08-26 18:15 UTC
Labels: duplicate
