### ISSUE TITLE
Test Singularity version ExploreASL Docker

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#507] opened 2021-04-28 08:36 UTC
We are working on making ExploreASL platform-independent, using the ExploreASL Docker that Michael created already a while ago. The disadvantage of Docker is that it uses root-access when executing, hence this is disabled by many server admins. Alternatives are Singularity and Podman, that don't require root access. Dockers can easily be converted to Singularity so we could set up a routine for this. Iman Brouwer (RNG, VUmc) converted our 1.6.0 beta-Docker to Singularity, which can be found here: `rng-img-dev1:/usr/local/apps/exploreasl/exploreasl-v1.6.0-beta.simg`

Note that we should run `setup_singularity-3.6.4` first on `rng-img-dev1` to define the singularity path. 

This issue is to:
1. Run and test this Singularity
2. add it to our Docker user manual [HERE] (https://docs.google.com/document/d/1_YfgIXrF0_4q3Q8DdnNQbRFyPh6E6oZ0Lj3LqkDtJgs/edit?usp=sharing), 
3. Include its computation time (from the module log-files) with the same test dataset

Who would like to do this?
 
Release notes:
Nothing to release

**Comment by ibrwr** [comment] 2021-04-28 08:46
Note that with a singularity you do not have elevated rights, so normal user permissions apply. Also by default only a few default paths like your home directory are mounted, other paths you have to bind explicitly yourself

**Comment by HenkMutsaerts** [comment] 2021-04-28 08:59
Thanks, we also have a GUI that we could try to implement, but it has an interactive interface to define a path to the data, so I don't know if you can easily mount a complete disk (e.g. /radshare in the case of rng-img-dev1) and that the user could use the GUI to choose a specific folder)

**Comment by maartenhammer** [comment] 2023-03-29 12:33
Duplicate of #1177

**Closed by maartenhammer** 2023-03-29 12:33 UTC
Labels: feature
